### PR TITLE
Use McMaster.NETCore.Plugins for assembly loading

### LINKED ISSUE #114: Use McMaster's DotNetCorePlugins
### Summary

Generators will be based on `netcoreapp2.0/2.1` and possibly provide a known configuration file, based on https://github.com/natemcmaster/DotNetCorePlugins

### Reasoning

The current model of targeting net461/netstandard1.6 is based on supporting both MSBuild and MSBuildCore running some task DLLs, AFAIK. Since some time, the generation is run as an external process via DotNetCliTool mechanism.

A `dotnet-codegen` exe is invoked, which is a netcoreapp which uses Roslyn to compile the project and loads generator DLLs that then provide the generated source. Which means that no matter what, the generator DLLs will be run as a netcoreapp *anyway*.

Using the DotNetCorePlugins project removes the burden of loading assemblies and all the dependency hell, and requiring generators to target `netcoreapp` will remove a lot of framework assemblies otherwise included as part of build output. An additional benefit is using it will unlock more APIs.

A separate benefit is that we can then provide new Sdk versions that reference `dotnet-codegen` targeting new netcoreapp versions so that generators can use new APIs etc.

No compatibility is lost because netcoreapp will still (via netstandard2.0+ support) support both current targets (netstandard1.6 and net461).

### PR DESCRIPTION
**Pull request by amis92**
* Engine uses `McMaster.NETCore.Plugins` package to resolve assemblies and dependencies, enabling generators to reference additional dependencies! 🎉
* Tasks deprecate `GeneratorAssemblySearchPaths` usage
* Tasks use `CodeGenerationRoslynPlugin` ItemGroup instead, which contains
  concrete assembly paths (instead of containing folder paths, as was previously)
* Engine targets `netcoreapp2.0` to reference McMaster package
* Tests use Amadevus.RecordGenerator NuGet generator for
  back-compat checks
* Tests.Generators use Bogus NuGet for NuGet dependency resolution check
* `CodeGeneration.Roslyn.Plugin.Sdk` MSBuild project Sdk created, to help build and package plugins correctly.
* Migrate to use VS2019/.NET Core SDK v3.1
* Rewritten Readme with a simpler demo and more advanced scenarios

Added https://github.com/AArnott/CodeGeneration.Roslyn/wiki/Migrations#v07 to help with migrations.

closes #114

CC @Pzixel 

TODO:
* [x] Update documentation, README etc.

### CODE REVIEW

**Comment by Pzixel** [comment]
Cool. The only bad thing about that is that I probably changing my job so I won't need a codegen soon. Waited for too long 😄 

Awesome work guys, anyway. Gonna update my library if it fits. I will check this when it gets into the nuget.

**Comment by AArnott** [comment]
Please do update the README as you say though.

**Comment by tedvanderveen** [comment]
Great work guys, this should fix the issue I'm facing right now!

**Comment by Pzixel** [comment]
And it still open. Guys, that issue blocks a lot of good stuff. Consider revisiting it soon?

**Comment by Pzixel** [comment]
I wonder if this going to merge before 2020

**Comment by amis92** [comment]
I'd like to announce I'm back, working on it. I have to admit, the "your code from 3 months ago could be written by someone else" saying is so true.

If someone want to help, don't hesitate. I'll probably run some tests, try to touch up documentation to the best of my abilities, and push a beta release since I really need some external input and testing.

**Comment by Pzixel** [comment]
I'd like to help but I won't be able to if there won't be a nuget package with it. 

My primary OS is windows so I only can build in docker. And the only sane way of running it in docker is pull items from nuget. Packing nuget locally and copying it via Dockerfile doesn't seem to be an easy task.

**Comment by amis92** [comment]
📝 I'm using `MSBuildWarningsAsMessages` feature of v15.0 (https://github.com/microsoft/msbuild/pull/1928).

**Comment by amis92** [comment]
I've added a Plugin.Sdk (first idea #113) to the mix, and I think quite extensive documentation in the readme.

@AArnott want to play with it, or merge and push out as a beta to let the people play?

**Comment by AArnott** [comment]
@amis92 Thanks again for putting this together. I'm not sure when I'll have time to play with it. Maybe next week. If I don't get back to you early next week feel free to complete anyway.

**Comment by amis92** [comment]
it's done - Frodo under mt doom - GIF

**Comment by amis92** [comment]
@Pzixel 

v0.7.5-alpha

**Comment by Pzixel** [comment]
> I wonder if this is going to merge before 2020

Well, it didn't... :)


*guess my origin* 

Thanks for PR, I'l try to manage to get to it soon.

**Pull request merged**
