### PR TITLE
#166: Fix path order for loading dependencies

### PR DESCRIPTION
**Pull request by cezarypiatek**
This should fix the problem with loading dependencies described here #166

### CODE REVIEW

**Comment by cezarypiatek** [comment]
Any chance of merging it?

**Comment by AArnott** [comment]
How does this compare to #114, @amis92? Since both PRs purport to fix the problem, which one should we merge?

**Comment by cezarypiatek** [comment]
This one can be closed. I don't need this merge anymore. Waiting for acceptance of this PR, I completely rewrote `CodeGeneration.Roslyn` because I spotted there a couple of other  different issues and the code was over-complicated.

**Comment by AArnott** [comment]
Thank you, @cezarypiatek

**Pull request closed without merging**
